version: "3.9"

services:
  api:
    build:
      context: ./api
      target: development
    ports:
      - 3001:3001
    volumes:
      - ./api:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
