version: "3.9"

x-node-app: &node-app
  image: node:alpine
  working_dir: /app
  command: npm run dev

services:
  api:
    <<: *node-app
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
  frontend:
    <<: *node-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  db:
    image: redis:alpine
    volumes:
      - /data
